import 'package:flutter/material.dart';
import 'package:mktbaz/app/modules/careers/components/title_card.dart';

class ExpansionTitle extends StatelessWidget {
  const ExpansionTitle({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {

    final List item =[
      ["a)","Why must I be a marketing researcher?","It is a choice only you can make.  You are now being trained by us to be one.  During the first few months (preferably not more than three), you have to think seriously about whether you want to be a marketing researcher.  But once you decide to stay whether you like it or not, we are going to try to make you a researcher of substance."],
      ["b)","How long does it take to be a researcher?", "If you have a basic degree (maybe not even necessary), if you can think (we understand that some of you can pretend to), you can write (especially English) and handle more than basic instructions, it will take you approximately two years to manage projects under the supervision of a Research Director.To be a full fledged researcher who we can allow to handle clients independently without endangering himself / herself, the client and the company, it takes minimally 3 years and a show of competency.To be an excellent researcher whom other researchers talk about, the process takes forever because when you stop learning you stop being excellent."],
      ["c)","Why does it take so much to become a marketing researcher?","No one is born a marketing researcher - we take this view for granted.  You are going to be paid while you learn.  You are not here to earn your salary as a trainee, neither do we see ourselves as paying you what you are worth since that will likely be nothing.  Most of the time until and unless you start learning to write proposals, do projects, analyse findings and make presentations – you are more a pain than a help.\n🏐While we are training and teaching you, your “work” is mainly useless.  Your draft proposals and draft reports generally cause us a lot of frustration, stress and we have to spend more time turning them into meaningful documents before they can go to clients.  Actually, we sometimes feel that we ought to charge trainee executives tuition fees for making professionals out of you at great ost to our mental and physical health."],
      ["d)","So why do we take in trainees?","Unlike other agencies, we prefer to train our own researchers than recruit from our competitors (we also do not believe that we can find anybody to meet our standards otherwise).  When we hire executives, we hire them with the view of them becoming one of our country managers (running one of our offices) one day.  We take our profession seriously, so competence and integrity are important to us even if it is unfashionable to claim that these days.  If you are not interested to go through some painful learning to be the best you can be, then you are not of much use to us - or seriously, anybody else."],
      ["e)","What kind of training do I get?","You will be thrown into the deep end from the start.  You learn very quickly to do real work, attend meetings, presentations and focus groups.  You will be assigned a mentor (usually a Research Director or Manager) and work in a team with more senior research executives.\nWhen you attend meetings and presentations, it is not for your personal pleasure.  You take notes, listen to how questions are asked,what answers are given and you learn.We use the ‘Thinking Man’ as our logo for a reason.  THINK!  It is amazing how many people expect to get through their training without thinking\nWork closely with your team, show your draft proposals and reports to your mentor so that he / she can check and correct your work.  How else can he be impressed (or otherwise) with your thinking capability, diligence and time management.  If you are set a deadline - meet it - if you cannot - tell your mentor why and how much time you need.  Deadlines always seem unreasonable but when you push yourself you will be surprised how easily you can meet them."],
      ["f)","Why do I always get more work to do than others?","Have you heard of the phrase “we are the victims of our own success”?  You get more work because of your ability to complete them quickly and properly.  When people are impressed with your reliability and ability, they come back to you.  Do you go back to a restaurant that serves lousy food?  Do you ask the plumber to fix your pipes in the bathroom when he flooded your kitchen?  Be thankful when everybody asks to work with you, that is a show of confidence - otherwise you may not make it past the first three months of your probation."],
      ["g)","If I made a mistake will it be held against me?","If you are a trainee, the mentor will be wise not to let you make mistakes against your will.  Bad things happen to researchers who make mistakes.  Whilst mistakes are generally not held against you in the early days of your training, remember that confidence is a strange thing.  Once lost it is hard to be regained.  Bad incidents linger in the memory and you have to work a lot harder to remove them.\nIn marketing research we dread Murphy.  His law has long arms in product tests, attribute ratings in questionnaires, preparation of test materials.  Believe us, anything that can go wrong will go wrong.  Always meticulously check and recheck things, even then Murphy pursues you relentlessly."],
      ["h)","Who do I go to if I have a problem?","Go first to your mentor.  If he / she is the problem go to another Research Director or Director.If you have a problem because of too much work refer to (f).  If “too much work” arises because you do not know how to do it, then ask for help from a senior researcher.  Do not pass the work to someone else - it would be wiser for you to learn how to do it.  Work always comes back that you passed the work to someone else."],
      ["i)","Is this a very stressful place to work?","Depending on who you ask, the answer could be “yes” or “no”.\nWe are very demanding on ourselves and on the people who work with us.  You are either going to be very good at what you do or you are not.  There is no in-between.\nWe are very demanding on ourselves and on the people who work with us.  You are either going to be very good at what you do or you are not.  There is no in-between.\n◯ Thinking about what a great job you are doing instead of how hard you are working,\n◯ Believing how much you are learning instead of how much work you are doing,\n◯ Discussing new ideas with positive minded colleagues instead of commiserating with losers about how difficult a project is\n◯ Developing the “I can” attitude instead of the “How can I?” self doubt"],
      ["j)","Do I have to come to work at 9:00 am since I worked late the night before?","Yes you do.  Your clients expect to be able to reach you when they call.  They do not know you had worked late or had conducted a focus group the previous night.\nIf you know you are going to be late, call the receptionist to inform clients that you are in an early morning meeting and will return calls as soon as you can."],
      ["l)"," Do I have to bother about the office and the property of the company?","You spend 10-12 hours a day in the office (half of your 24 hours day or two-thirds of your working time) - more than the time you spend in your own home.  You want to feel the space belong to you so make it comfortable, clean, put things back where they belong.\nTreat the things in the office like you would your own belongings (you never know, one day it might be given to you).\nConvey a sense of pride that this is your office, your company.  Clients and visitors notice how the staff feel for their company very quickly."],
      ["m)","Why is the company so security conscious – it feels like the Gestapo HQ?","Next to quality, the most important thing in our business is security.  You must not take these things lightly :\nBe vigilant.  Security consciousness should be second nature to us.  We must protect our client’s properties, projects and interests at all time.\nThis is not Gestapo!  We have not instituted 24 hours interrogation of culprits yet."],
      ["o)"," Can I delegate work to other newer trainee executives?","Think before you even ask this question.  Would you give away a prized treasure to someone else?  Who do you think will learn and progress faster than you in the company?"],
      ["p)","Can I pass my time here doing as little as possible since I only want a job?","You are in the wrong company.  You probably can fool some people some of the time by appearing to be busy and working hard.  But you can hardly fool the Directors - they have seen this dysfunctional personality type before and you are quickly shown the door.\n\nOur advice, change your attitude fast, you don’t know what a danger you are to yourself."],
      ["q)","When do I know I am going to make it as a top notch researcher?","When you feel coming to work is exciting.  When you are captivated and absorbed by the projects you work on.  When the clients you work with call you personally to take briefs, provide more information or just to help them get something.  When you find a well written proposal or report so beautiful and elegant you wish your name was on it.  When you want to do more than 110% for your clients because they always appreciate what you do for them.  When you can go without sleep for a night and still feel ready to face a new day of challenges.\n\nIf you feel lukewarm about all the things above - it’s time to call it a day and look for another job."],
      ["r)","Will I make a lot of money as a researcher?","You have probably heard this many times.  For us, marketing research is a passion.  We just want to do a great job, enjoy what we are working on and experience the intellectual growth.  We know ultimately the recognition, fulfillment and money will be there.\nYou will be sought after and you will be paid top dollars.  But first – if you don’t enjoy what you do, no amount of money will make you happy."],
    ];

    return Column(
      children: [
        Text("THE MAKING OF ACORN RESEARCHERS:",style: TextStyle(fontSize: 30,fontWeight: FontWeight.w100,color: Colors.black)),
        Divider(),
        ...List.generate(item.length, (index) => TitleCard(
            item_index: item[index][0],
            title: item[index][1],
            sub_title:item[index][2])),
      ],
    );
  }
}